version: "3.8"

volumes:
  gems:
  db:

services:
  app: &default
    hostname: app
    command: bash -c "rm -f /projetobonus/tmp/pids/server.pid &&  bin/rails s -p 3000 -b 0.0.0.0"
    stdin_open: true
    tty: true
    env_file: .env
    build:
      context: .
      target: development
      args:
        - BUNDLER_VERSION=${BUNDLER_VERSION:-2.1.4}
        - BUNDLE_PATH=/bundle
        - APP_USER_ID=${APP_USER_ID:-1000}
        - APP_GROUP_ID=${APP_GROUP_ID:-1000}
    volumes:
      - .:/projetobonus/
      - gems:/bundle/
      - ~/.gitconfig:/etc/gitconfig
    ports:
      - 3000:3000
      - 4000:4000
    depends_on:
      - db
      - redis
      - inbox
      - sidekiq

  sidekiq:
    <<: *default
    ports: []
    command: bash -c "rm -f /tmp/pids/sidekiq.pid && bundle exec sidekiq"
    depends_on:
      - db
      - redis
      - inbox

  db:
    hostname: db
    image: postgres:12-alpine
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bonus12345
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    hostname: redis
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 6379
    volumes:
      - /data

  inbox:
    hostname: mail
    image: schickling/mailcatcher
    ports:
      - 5000:1080